### ISSUE TITLE
Validar campo de número de teléfono a 10 dígitos

### ISSUE THREAD

**Issue by danyael031** [ProyectoMigalaOficial/formulario-Registro-2#5]
<https://surveyjs.io/Examples/Library/?id=custom-widget-inputmask&platform=Angular2&theme=default#content-js>

**Comment by joshuansu0897** [comment]
En ese ejemplo veo que usan un número (como en estados unidos +1) `+#(###)-###-####`, pero en México es +52. 

O sea, en nuestro caso debería ser  `+##(###)-###-####` -> `+52(632)-944-0677` (este si sería un número válido en México) 

pero, si usamos ese `inputFormat` solo funcionará en regiones que usan dos dígitos en la región como `+52` cualquier mexicano que viva en USA y tenga un número estadounidense no puede inscribirse, porque ellos tienen `+1`

**Comment by danyael031** [comment]
Una manera rápida de resolver esto es removiendo la clave telefónica por país. Se puede agregar lógica en el formulario para desactivar el campo de número telefónico en caso de que el usuario sea extranjero.

La alternativa difícil (que de momento no la veo necesaria) sería obtener las claves por país desde una api y agregar un dropdown para seleccionarlo.

La siguiente API contiene las claves telefónicas de todos los países:
<https://restcountries.com/v2/all>

**Comment by danyael031** [comment]
Por cierto, el número de teléfono debería de quedar a 10 dígitos sin la clave por país.
